server:
  port: 8080
logging:
  level:
    root: info
spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  data:
    mongodb:
#      username: ${MONGO_USERNAME:mongo}
#      password: ${MONGO_PASSWORD:mongo}
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: "station_management"
      authentication-database: "admin"
      auto-index-creation: true
